mocknet:
	@./deploy.sh mocknet ${NODES} ${PEER} ${PEER_API}

testnet:
	@./deploy.sh testnet ${NODES} ${PEER} ${PEER_API}

mainnet:
	@./deploy.sh mainnet ${NODES} ${PEER} ${PEER_API}

clean:
	helm uninstall mocknet
