{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lastnode.serviceAccountName" . }}
  labels:
{{ include "lastnode.labels" . | nindent 4 }}
{{- end -}}
