apiVersion: v2
name: lastnode-stack
description: Deploys a LastNode stack with options to enable or disable some services
type: application
version: 0.2.0

appVersion: 0.2.0

dependencies:
  - name: common
    repository: file://../common
    version: 0.1.0

  - name: gateway
    repository: file://../gateway
    version: 0.1.0
    condition: gateway.enabled

  - name: lastnode
    repository: file://../lastnode
    version: 0.1.0
    condition: lastnode.enabled

  - name: bifrost
    repository: file://../bifrost
    version: 0.1.0
    condition: bifrost.enabled

  - name: midgard
    repository: file://../midgard
    version: 0.1.0
    condition: midgard.enabled

  - name: bitcoin-daemon
    repository: file://../bitcoin-daemon
    version: 0.1.0
    condition: bitcoin-daemon.enabled

  - name: ethereum-daemon
    repository: file://../ethereum-daemon
    version: 0.1.0
    condition: ethereum-daemon.enabled

  - name: avalanche-daemon
    repository: file://../avalanche-daemon
    version: 0.1.0
    condition: avalanche-daemon.enabled
